[package]
name = "oxi-rmw"
version = "0.1.0"
authors = ["andy5995 <andy400-dev@yahoo.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3.15"
dirs = "3.0.1"
